executable   = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTWJetsToLNu_condorJobs/TTWJetsToLNu_1.sh
arguments    = $(ClusterId)$(ProcId)
output       = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTWJetsToLNu_condorJobs/output/TTWJetsToLNu_1.$(ClusterId).$(ProcId).out
error        = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTWJetsToLNu_condorJobs/error/TTWJetsToLNu_1.$(ClusterId).$(ProcId).err
log          = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTWJetsToLNu_condorJobs/log/TTWJetsToLNu_1.$(ClusterId).log
+JobFlavour  = "tomorrow"
queue
