executable   = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/TTGJets_condorJobs/TTGJets_1.sh
arguments    = $(ClusterId)$(ProcId)
output       = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/TTGJets_condorJobs/output/TTGJets_1.$(ClusterId).$(ProcId).out
error        = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/TTGJets_condorJobs/error/TTGJets_1.$(ClusterId).$(ProcId).err
log          = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/TTGJets_condorJobs/log/TTGJets_1.$(ClusterId).log
+JobFlavour  = "tomorrow"
queue
