executable   = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/ST_tW_top_5f_condorJobs/ST_tW_top_5f_3.sh
arguments    = $(ClusterId)$(ProcId)
output       = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/ST_tW_top_5f_condorJobs/output/ST_tW_top_5f_3.$(ClusterId).$(ProcId).out
error        = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/ST_tW_top_5f_condorJobs/error/ST_tW_top_5f_3.$(ClusterId).$(ProcId).err
log          = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit1/ST_tW_top_5f_condorJobs/log/ST_tW_top_5f_3.$(ClusterId).log
+JobFlavour  = "tomorrow"
queue
