executable   = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTToSemiLeptonic_condorJobs/TTToSemiLeptonic_11.sh
arguments    = $(ClusterId)$(ProcId)
output       = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTToSemiLeptonic_condorJobs/output/TTToSemiLeptonic_11.$(ClusterId).$(ProcId).out
error        = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTToSemiLeptonic_condorJobs/error/TTToSemiLeptonic_11.$(ClusterId).$(ProcId).err
log          = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/TTToSemiLeptonic_condorJobs/log/TTToSemiLeptonic_11.$(ClusterId).log
+JobFlavour  = "tomorrow"
queue
