executable   = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/DYJetsToLL_M-50_condorJobs/DYJetsToLL_M-50_23.sh
arguments    = $(ClusterId)$(ProcId)
output       = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/DYJetsToLL_M-50_condorJobs/output/DYJetsToLL_M-50_23.$(ClusterId).$(ProcId).out
error        = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/DYJetsToLL_M-50_condorJobs/error/DYJetsToLL_M-50_23.$(ClusterId).$(ProcId).err
log          = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/DYJetsToLL_M-50_condorJobs/log/DYJetsToLL_M-50_23.$(ClusterId).log
+JobFlavour  = "tomorrow"
queue
