executable   = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/ST_t-channel_top_5f_condorJobs/ST_t-channel_top_5f_4.sh
arguments    = $(ClusterId)$(ProcId)
output       = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/ST_t-channel_top_5f_condorJobs/output/ST_t-channel_top_5f_4.$(ClusterId).$(ProcId).out
error        = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/ST_t-channel_top_5f_condorJobs/error/ST_t-channel_top_5f_4.$(ClusterId).$(ProcId).err
log          = /afs/cern.ch/work/s/sbaradia/public/ChargedHiggs/ChargedHiggsAnalysis/MakeJobsAndSend/JobCards_2017_submit/ST_t-channel_top_5f_condorJobs/log/ST_t-channel_top_5f_4.$(ClusterId).log
+JobFlavour  = "tomorrow"
queue
